### ISSUE TITLE
How to use it, please example!

### ISSUE THREAD

**Issue by thearabbit** [peerlibrary/meteor-async#6]
How to use it, please example!

**Comment by mitar** [comment]
See [documentation here](https://github.com/caolan/async).

**Comment by thearabbit** [comment]
Sorry, I don't understand.
Does we use it to call `Meteor method` on client instead of `Meteor.call`?
```js
// Server
Meteor.methods({
   myMethod().........
})

// Client call via async
.............

```
could you explain?

**Comment by mitar** [comment]
No. This package just provides Meteor package for [this library](https://github.com/caolan/async).

**Comment by thearabbit** [comment]
Thanks again.
